name: CI

on:
  push:
  pull_request:
  release:
    types: [published]

jobs:
  build-no-wifi:
    name: Build (no WiFi / HoRNDIS)
    runs-on: macos-14
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create output directory and zip files
        run: |
          mkdir -p Output
          zip --exclude '*.git*' --exclude '*.github*' --exclude '*Output*' -r -X "Output/${{ github.event.repository.name }}-${{github.ref_name}}.zip" .

      - name: Upload to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: HoRNDIS
          path: Output/*.zip
          retention-days: 7

      - name: Upload to Release
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v2
        with:
          files: Output/*.zip

  
          
  build-universal:
    name: Universal Build
    runs-on: macos-14
    needs: [build-no-wifi]
    if: github.event_name == 'release'
    steps:
      - name: Create summary
        run: |
          echo "# Build Summary" > $GITHUB_STEP_SUMMARY
          echo "All builds completed successfully. The following builds are available:" >> $GITHUB_STEP_SUMMARY
          echo "- Intel WiFi" >> $GITHUB_STEP_SUMMARY
          echo "- No WiFi / HoRNDIS / native AirPort" >> $GITHUB_STEP_SUMMARY